config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
        end
      end
    end
  end
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :likes, only: [:create]
      resources :comments, only: [:index, :new, :create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy, counter_cache: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user
      @recent_posts = @user.most_recent_posts
    else
      flash[:alert] = 'User not found'
      redirect_to root_path
    end
  end
end

app/views/users/index.html.erb
<% if user_signed_in? %>
<div> Welcome <%= current_user.email %> </div>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= button_to "Sign in", new_user_session_path %>
<% end %>

<div class="users">
<% @users.each do |user| %>
<%= render 'shared/user', user:user %>
<% end %>
</div>

app/views/users/show.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
  <div class='d-flex justify-content-center'>
    <div class='col-md-4 text-center'>
      <h2>Sign up</h2>

      <div class="form-group">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email", class:"form-control" %>
      </div>

      <div class="form-group">
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password", placeholder: "Password", class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "Confirm Password", class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :name, placeholder: "Names", class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :photo_link, placeholder: "Photo", class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_area :bio, placeholder: "Bio", class:"form-control" %>
      </div>
      <div class="actions">
        <%= f.submit "Sign up", class:"btn btn-primary" %>
      </div>

      <%= render "devise/shared/links" %>
    </div>
  </div>
<% end %>