config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
        end
      end
    end
  end
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :likes, only: [:create]
      resources :comments, only: [:index, :new, :create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

end

app/views/shared/_comments.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.user.name%> :<%= comment.text %></p>
    </div>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="post">
<%=link_to user_post_path(user, post) do %>
<div class="single-post-cont">
<div class="post-title">
<h1><%= post.title %></h1>
</div>
<div class="post-content">
<p><%= post.text %></p>
</div>
<div class="interactions">
<p>comments: <%= post.comments_counter %></p>
<p>likes: <%= post.likes_counter %></p>
</div>
</div>
<% end %>
</div>

app/views/shared/_user.html.erb
<div class="user-container">
<%=link_to user_path(user) do %>
<div class="container-components">
<div class="img-container">
<img src="<%= user.photo_link %>"
alt="<%= user.name %>" />
</div>
<div class="userpost-container">
<h1 class="user-name"><%= user.name %></h1>
<p class="user-post">Number of posts: <%= user.posts_counter %></p>
</div>
</div>
<% end %>

</div>