config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
        end
      end
    end
  end
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :likes, only: [:create]
      resources :comments, only: [:index, :new, :create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_create :increment_user_posts_counter
  before_create :set_defaults

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end

  def set_defaults
    self.likes_counter ||= 0
    self.comments_counter ||= 0
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  # skip_before_action :authenticate_user!
  protect_from_forgery with: :null_session
  protect_from_forgery with: :exception, except: [:create]
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])

    if @posts
      render json: { status: 'Success', message: 'Bravo!', data: @posts }, status: :ok
    else
      render json: { status: 'Error', message: 'OOPSY Daisy!', errors: @posts.errors }, status: :bad_request
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :comments_counter, :likes_counter)
  end
end

app/controllers/concerns/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except:
  %i[index show]

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:author).find(params[:id])

    if @post
      @user = @post.author
      @comments = @post.comments

    else
      flash[:alert] = 'Post not found'
      redirect_to user_posts_path(params[:user_id])
    end
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post created successfully!'
    else
      puts @user
      puts @post.errors.full_messages
      flash.now[:errors] = 'Invalid post!'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :likes_counter, :comments_counter)
  end
end

app/views/posts/index.html.erb
<div class="posts-container">
<div class="users">
<%= render 'shared/user', user:@user %>
</div>

<div class="posts">
<h2>All Posts</h2>

<%=link_to "Add post", new_user_post_path(@user)%>

<% @posts.each do |post| %>
<%= render 'shared/post', post: post, user:@user %>

<div class="post-content">
<%= link_to "Add Comment", new_user_post_comment_path(@user, post) %>

<%= form_with url: user_post_likes_path(post.author.id, post.id) do |form| %>

<%= form.submit 'Like' %>
<% end %>

<% if can?(:destroy, @post) %>
        <%= button_to 'Delete Post', user_post_path(@post.author_id, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'delete-button' %>
      <% end %>
</div>

<% if post.recent_comments.present? %>
<% comments = post.recent_comments %>
<%= render "shared/comments", comments:comments %>
<% end %>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class= "post-form">
  <h2 class= "create-post">Create a post</h2>

  <%# <%= form_with model: @post, url: user_posts_path(@user) do |f| %> 
  <%= form_with(model: [@user, @post], url: user_posts_path(@user)) do |f| %>
    <div class= "title-input">
      <%= f.label :title %>
      <%= f.text_field :title, required: true %>
    </div>

    <div class= "comment-input">
      <%= f.label :text %>
      <%= f.text_field :text, required: true %>
    </div>
<!-- Add fields for likes_counter and comments_counter -->
    <div class="likes-counter-input">
      <%= f.label :likes_counter %>
      <%= f.number_field :likes_counter, value: 0, min: 0 %>
    </div>

    <div class="comments-counter-input">
      <%= f.label :comments_counter %>
      <%= f.number_field :comments_counter, value: 0, min: 0 %>
    </div>
    
    <div class= "submit">
      <%= f.submit "Submit" %>
    </div>
    <% if @post.errors.any? %>
  <div class="error-messages">
    <h2>Errors:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
         <% end %>
    </ul>
  </div>
  <% end %>
 <% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-show">
<div class="post-show">

<div class="post-title-show">
<h1><%= @post.title %></h1>

<div class="post-interact">
<p>comments: <%= @post.comments_counter %></p>
<p>likes: <%= @post.likes_counter %></p>
</div>
</div>

<div>
<p><%= @post.text %></p>
</div>

</div>
<div class= "shared-comment-cont">
<div class="shared-comments">
<%= link_to "Add Comment", new_user_post_comment_path(@user, @post) %>
<%= form_with url: user_post_likes_path(@post.author.id, @post.id) do |form| %>
<%= form.submit 'Like' %>
<% end %>

<% if can? :destroy, @post %>
<%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'delete-button' %>
<% end %>

</div>
<h2>Comments</h2>
<%= render "shared/comments", comments:@comments %>
</div>

</div>